server:
  port: 8900
task:
  pool:
    corePoolSize : 20
    maxPoolSize : 40
    keepAliveSeconds : 300
    queueCapacity : 50

test:
  messsage : hello_world

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.181.166:3306/new_agent_erp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: jcc
    password: jcc

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
